services:
  - type: web
    name: mmaudio-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      wget https://github.com/OpenMOSS/MMAudio/archive/refs/heads/main.zip
      unzip main.zip
      mv MMAudio-main MMAudio
      cd MMAudio && pip install -e .
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
